# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'mainwindow.ui'
##
## Created by: Qt User Interface Compiler version 6.5.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QFrame, QGraphicsView, QLabel,
    QMainWindow, QMenuBar, QPushButton, QSizePolicy,
    QStatusBar, QTextEdit, QWidget)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(737, 359)
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.label_2 = QLabel(self.centralwidget)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(10, 100, 61, 16))
        self.label = QLabel(self.centralwidget)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(10, 80, 61, 16))
        self.label_3 = QLabel(self.centralwidget)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(10, 160, 51, 16))
        self.txtLongitude = QLabel(self.centralwidget)
        self.txtLongitude.setObjectName(u"txtLongitude")
        self.txtLongitude.setGeometry(QRect(70, 100, 81, 18))
        self.txtLongitude.setFrameShape(QFrame.Panel)
        self.txtLongitude.setFrameShadow(QFrame.Sunken)
        self.txtSpeed = QLabel(self.centralwidget)
        self.txtSpeed.setObjectName(u"txtSpeed")
        self.txtSpeed.setGeometry(QRect(70, 160, 61, 18))
        self.txtSpeed.setFrameShape(QFrame.Panel)
        self.txtSpeed.setFrameShadow(QFrame.Sunken)
        self.txtLatitude = QLabel(self.centralwidget)
        self.txtLatitude.setObjectName(u"txtLatitude")
        self.txtLatitude.setGeometry(QRect(70, 80, 81, 18))
        self.txtLatitude.setFrameShape(QFrame.Panel)
        self.txtLatitude.setFrameShadow(QFrame.Sunken)
        self.label_4 = QLabel(self.centralwidget)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(10, 140, 61, 16))
        self.exitButton = QPushButton(self.centralwidget)
        self.exitButton.setObjectName(u"exitButton")
        self.exitButton.setGeometry(QRect(640, 300, 84, 32))
        self.txtHeading = QLabel(self.centralwidget)
        self.txtHeading.setObjectName(u"txtHeading")
        self.txtHeading.setGeometry(QRect(70, 140, 61, 18))
        self.txtHeading.setFrameShape(QFrame.Panel)
        self.txtHeading.setFrameShadow(QFrame.Sunken)
        self.txtTime = QLabel(self.centralwidget)
        self.txtTime.setObjectName(u"txtTime")
        self.txtTime.setGeometry(QRect(70, 60, 151, 20))
        self.txtTime.setFrameShape(QFrame.Panel)
        self.txtTime.setFrameShadow(QFrame.Sunken)
        self.label_7 = QLabel(self.centralwidget)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setGeometry(QRect(10, 60, 51, 16))
        self.label_5 = QLabel(self.centralwidget)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(10, 120, 61, 16))
        self.label_8 = QLabel(self.centralwidget)
        self.label_8.setObjectName(u"label_8")
        self.label_8.setGeometry(QRect(10, 40, 51, 16))
        self.txtStatus = QLabel(self.centralwidget)
        self.txtStatus.setObjectName(u"txtStatus")
        self.txtStatus.setGeometry(QRect(70, 40, 61, 16))
        self.txtStatus.setFrameShape(QFrame.Panel)
        self.txtStatus.setFrameShadow(QFrame.Sunken)
        self.label_10 = QLabel(self.centralwidget)
        self.label_10.setObjectName(u"label_10")
        self.label_10.setGeometry(QRect(10, 180, 49, 20))
        self.label_11 = QLabel(self.centralwidget)
        self.label_11.setObjectName(u"label_11")
        self.label_11.setGeometry(QRect(10, 200, 49, 16))
        self.txtHDOP = QLabel(self.centralwidget)
        self.txtHDOP.setObjectName(u"txtHDOP")
        self.txtHDOP.setGeometry(QRect(70, 180, 61, 16))
        self.txtHDOP.setFrameShape(QFrame.Panel)
        self.txtHDOP.setFrameShadow(QFrame.Sunken)
        self.txtVDOP = QLabel(self.centralwidget)
        self.txtVDOP.setObjectName(u"txtVDOP")
        self.txtVDOP.setGeometry(QRect(70, 200, 61, 16))
        self.txtVDOP.setFrameShape(QFrame.Panel)
        self.txtVDOP.setFrameShadow(QFrame.Sunken)
        self.txtAltitude = QLabel(self.centralwidget)
        self.txtAltitude.setObjectName(u"txtAltitude")
        self.txtAltitude.setGeometry(QRect(70, 120, 61, 16))
        self.txtAltitude.setFrameShape(QFrame.Panel)
        self.txtAltitude.setFrameShadow(QFrame.Sunken)
        self.label_9 = QLabel(self.centralwidget)
        self.label_9.setObjectName(u"label_9")
        self.label_9.setGeometry(QRect(130, 120, 81, 16))
        self.label_13 = QLabel(self.centralwidget)
        self.label_13.setObjectName(u"label_13")
        self.label_13.setGeometry(QRect(130, 160, 49, 16))
        self.txtMode = QLabel(self.centralwidget)
        self.txtMode.setObjectName(u"txtMode")
        self.txtMode.setGeometry(QRect(130, 40, 49, 16))
        self.txtMode.setFrameShape(QFrame.Panel)
        self.txtMode.setFrameShadow(QFrame.Sunken)
        self.label_6 = QLabel(self.centralwidget)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(10, 220, 49, 16))
        self.txtGrid = QLabel(self.centralwidget)
        self.txtGrid.setObjectName(u"txtGrid")
        self.txtGrid.setGeometry(QRect(70, 220, 61, 16))
        self.txtGrid.setFrameShape(QFrame.Panel)
        self.txtGrid.setFrameShadow(QFrame.Sunken)
        self.txtSatellites = QTextEdit(self.centralwidget)
        self.txtSatellites.setObjectName(u"txtSatellites")
        self.txtSatellites.setGeometry(QRect(230, 10, 220, 280))
        font = QFont()
        font.setFamilies([u"Courier"])
        self.txtSatellites.setFont(font)
        self.toggleLogging = QPushButton(self.centralwidget)
        self.toggleLogging.setObjectName(u"toggleLogging")
        self.toggleLogging.setGeometry(QRect(130, 250, 84, 32))
        self.label_12 = QLabel(self.centralwidget)
        self.label_12.setObjectName(u"label_12")
        self.label_12.setGeometry(QRect(10, 250, 111, 20))
        self.viewSatellites = QGraphicsView(self.centralwidget)
        self.viewSatellites.setObjectName(u"viewSatellites")
        self.viewSatellites.setGeometry(QRect(450, 10, 280, 280))
        brush = QBrush(QColor(0, 0, 0, 255))
        brush.setStyle(Qt.NoBrush)
        self.viewSatellites.setBackgroundBrush(brush)
        brush1 = QBrush(QColor(255, 255, 255, 255))
        brush1.setStyle(Qt.NoBrush)
        self.viewSatellites.setForegroundBrush(brush1)
        self.label_14 = QLabel(self.centralwidget)
        self.label_14.setObjectName(u"label_14")
        self.label_14.setGeometry(QRect(10, 10, 221, 16))
        font1 = QFont()
        font1.setPointSize(10)
        font1.setBold(True)
        self.label_14.setFont(font1)
        self.txtCount = QLabel(self.centralwidget)
        self.txtCount.setObjectName(u"txtCount")
        self.txtCount.setGeometry(QRect(150, 10, 61, 16))
        self.txtCount.setFrameShape(QFrame.Panel)
        self.txtCount.setFrameShadow(QFrame.Sunken)
        self.txtCount.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 737, 28))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)

        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"QtGPS", None))
        self.label_2.setText(QCoreApplication.translate("MainWindow", u"Longitude:", None))
        self.label.setText(QCoreApplication.translate("MainWindow", u"Latitude:", None))
        self.label_3.setText(QCoreApplication.translate("MainWindow", u"Speed:", None))
        self.txtLongitude.setText(QCoreApplication.translate("MainWindow", u"0", None))
        self.txtSpeed.setText(QCoreApplication.translate("MainWindow", u"0", None))
        self.txtLatitude.setText(QCoreApplication.translate("MainWindow", u"0", None))
        self.label_4.setText(QCoreApplication.translate("MainWindow", u"Heading:", None))
        self.exitButton.setText(QCoreApplication.translate("MainWindow", u"Exit", None))
        self.txtHeading.setText(QCoreApplication.translate("MainWindow", u"0", None))
        self.txtTime.setText("")
        self.label_7.setText(QCoreApplication.translate("MainWindow", u"Time:", None))
        self.label_5.setText(QCoreApplication.translate("MainWindow", u"Altitude:", None))
        self.label_8.setText(QCoreApplication.translate("MainWindow", u"Fix:", None))
        self.txtStatus.setText(QCoreApplication.translate("MainWindow", u"0", None))
        self.label_10.setText(QCoreApplication.translate("MainWindow", u"HDOP:", None))
        self.label_11.setText(QCoreApplication.translate("MainWindow", u"VDOP:", None))
        self.txtHDOP.setText(QCoreApplication.translate("MainWindow", u"0", None))
        self.txtVDOP.setText(QCoreApplication.translate("MainWindow", u"0", None))
        self.txtAltitude.setText(QCoreApplication.translate("MainWindow", u"0", None))
        self.label_9.setText(QCoreApplication.translate("MainWindow", u"m (WGS84)", None))
        self.label_13.setText(QCoreApplication.translate("MainWindow", u"m/sec", None))
        self.txtMode.setText(QCoreApplication.translate("MainWindow", u"0", None))
        self.label_6.setText(QCoreApplication.translate("MainWindow", u"Grid:", None))
        self.txtGrid.setText("")
        self.toggleLogging.setText(QCoreApplication.translate("MainWindow", u"Start", None))
        self.label_12.setText(QCoreApplication.translate("MainWindow", u"GPX Data Logging:", None))
        self.label_14.setText(QCoreApplication.translate("MainWindow", u"GPS Tool (gpsd client)", None))
        self.txtCount.setText(QCoreApplication.translate("MainWindow", u"0", None))
    # retranslateUi

